# Generated by Django 5.1.7 on 2025-03-23 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('WORDS', 'Random Words'), ('PARAGRAPH', 'Paragraph'), ('CODE', 'Code Snippet')], max_length=20)),
                ('content', models.TextField()),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TypingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('WORDS', 'Random Words'), ('PARAGRAPH', 'Paragraph'), ('CODE', 'Code Snippet')], max_length=20)),
                ('wpm', models.IntegerField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('errors', models.IntegerField()),
                ('test_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
